apiVersion: v1
kind: Service
metadata:
  name: {{ include "shop-chat.ui.fullname" . }}
  labels:
    {{- include "shop-chat.labels" . | nindent 4 }}
    {{- include "shop-chat.ui.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "shop-chat.ui.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
